  services:
    pgvector:
      image: 'pgvector/pgvector:pg16'
      environment:
        - 'POSTGRES_DB=roadmaps'
        - 'POSTGRES_PASSWORD=atul2192'
        - 'POSTGRES_USER=atul'
      labels:
        - "org.springframework.boot.service-connection=postgres"
      ports:
        - '5433:5432'
